"""add models

Revision ID: 0d450746331b
Revises: cd160b81ee30
Create Date: 2026-02-08 03:09:08.566196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d450746331b'
down_revision: Union[str, Sequence[str], None] = 'cd160b81ee30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_15m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time', 'id')
    )
    op.create_table('candles_1d',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time', 'id')
    )
    op.create_table('candles_1h',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time', 'id')
    )
    op.create_table('candles_1m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time', 'id')
    )
    op.create_table('candles_4h',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candles_4h')
    op.drop_table('candles_1m')
    op.drop_table('candles_1h')
    op.drop_table('candles_1d')
    op.drop_table('candles_15m')
    # ### end Alembic commands ###
