"""add candles_1m table

Revision ID: 17932b9b43e4
Revises: 
Create Date: 2026-02-03 00:32:43.657052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17932b9b43e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_1m',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('ignore', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_candles_1m_symbol_interval_open_time')
    )
    op.create_index('ix_candles_1m_symbol_interval_open_time', 'candles_1m', ['symbol', 'interval', 'open_time'], unique=False)
    op.drop_table('health_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ok', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('health_check_pkey'))
    )
    op.drop_index('ix_candles_1m_symbol_interval_open_time', table_name='candles_1m')
    op.drop_table('candles_1m')
    # ### end Alembic commands ###
