"""fresh candle tables baseline

Revision ID: 1816052531b4
Revises: 535cf59da3b8
Create Date: 2026-02-15 14:50:16.251786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1816052531b4'
down_revision: Union[str, Sequence[str], None] = '535cf59da3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_2m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_time', sa.BigInteger(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time')
    )
    op.create_index(op.f('ix_candles_2m_id'), 'candles_2m', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candles_2m_id'), table_name='candles_2m')
    op.drop_table('candles_2m')
    # ### end Alembic commands ###
