"""5m oi

Revision ID: 1ac53c07e9d5
Revises: aaea139cabe8
Create Date: 2026-03-01 16:29:54.420084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac53c07e9d5'
down_revision: Union[str, Sequence[str], None] = 'aaea139cabe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_interest_5m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('oi_notional', sa.Float(), nullable=False),
    sa.Column('open_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_interest_5m')
    # ### end Alembic commands ###
