"""fresh candle tables baseline

Revision ID: 1ba0af329c81
Revises: 25dace1276d6
Create Date: 2026-02-13 14:26:45.318486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba0af329c81'
down_revision: Union[str, Sequence[str], None] = '25dace1276d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_1d', sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_1h', sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_1m', sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_4h', sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_4h', 'lk_at')
    op.drop_column('candles_1m', 'lk_at')
    op.drop_column('candles_1h', 'lk_at')
    op.drop_column('candles_1d', 'lk_at')
    op.drop_column('candles_15m', 'lk_at')
    # ### end Alembic commands ###
