"""add cdx candle tables

Revision ID: 1d9300ad9fe8
Revises: 7b908c7eab06
Create Date: 2026-02-06 19:34:57.985257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9300ad9fe8'
down_revision: Union[str, Sequence[str], None] = '7b908c7eab06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdx_candles_15m', 'event_time')
    op.drop_column('cdx_candles_1d', 'event_time')
    op.drop_column('cdx_candles_1h', 'event_time')
    op.drop_column('cdx_candles_1m', 'event_time')
    op.drop_column('cdx_candles_4h', 'event_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdx_candles_4h', sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_1m', sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_1h', sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_1d', sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_15m', sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
