"""add models

Revision ID: 2116e08072b5
Revises: c884f1a301af
Create Date: 2026-02-08 00:48:49.792412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2116e08072b5'
down_revision: Union[str, Sequence[str], None] = 'c884f1a301af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('first_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_15m', sa.Column('last_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_15m', sa.Column('taker_buy_base_volume', sa.Float(), nullable=False))
    op.add_column('candles_15m', sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_15m_symbol_time'), table_name='candles_15m')
    op.drop_constraint(op.f('uq_15m_symbol_time'), 'candles_15m', type_='unique')
    op.drop_column('candles_15m', 'id')
    op.add_column('candles_1d', sa.Column('first_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_1d', sa.Column('last_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_1d', sa.Column('taker_buy_base_volume', sa.Float(), nullable=False))
    op.add_column('candles_1d', sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_1d_symbol_time'), table_name='candles_1d')
    op.drop_constraint(op.f('uq_1d_symbol_time'), 'candles_1d', type_='unique')
    op.drop_column('candles_1d', 'id')
    op.add_column('candles_1h', sa.Column('first_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_1h', sa.Column('last_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_1h', sa.Column('taker_buy_base_volume', sa.Float(), nullable=False))
    op.add_column('candles_1h', sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_1h_symbol_time'), table_name='candles_1h')
    op.drop_constraint(op.f('uq_1h_symbol_time'), 'candles_1h', type_='unique')
    op.drop_column('candles_1h', 'id')
    op.add_column('candles_1m', sa.Column('first_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_1m', sa.Column('last_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_1m', sa.Column('taker_buy_base_volume', sa.Float(), nullable=False))
    op.add_column('candles_1m', sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_1m_symbol_time'), table_name='candles_1m')
    op.drop_constraint(op.f('uq_1m_symbol_time'), 'candles_1m', type_='unique')
    op.drop_column('candles_1m', 'id')
    op.add_column('candles_4h', sa.Column('first_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_4h', sa.Column('last_trade_id', sa.BigInteger(), nullable=False))
    op.add_column('candles_4h', sa.Column('taker_buy_base_volume', sa.Float(), nullable=False))
    op.add_column('candles_4h', sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_4h_symbol_time'), table_name='candles_4h')
    op.drop_constraint(op.f('uq_4h_symbol_time'), 'candles_4h', type_='unique')
    op.drop_column('candles_4h', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_4h', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_4h_symbol_time'), 'candles_4h', ['symbol', 'open_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_4h_symbol_time'), 'candles_4h', ['symbol', 'open_time'], unique=False)
    op.drop_column('candles_4h', 'taker_buy_quote_volume')
    op.drop_column('candles_4h', 'taker_buy_base_volume')
    op.drop_column('candles_4h', 'last_trade_id')
    op.drop_column('candles_4h', 'first_trade_id')
    op.add_column('candles_1m', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_1m_symbol_time'), 'candles_1m', ['symbol', 'open_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_1m_symbol_time'), 'candles_1m', ['symbol', 'open_time'], unique=False)
    op.drop_column('candles_1m', 'taker_buy_quote_volume')
    op.drop_column('candles_1m', 'taker_buy_base_volume')
    op.drop_column('candles_1m', 'last_trade_id')
    op.drop_column('candles_1m', 'first_trade_id')
    op.add_column('candles_1h', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_1h_symbol_time'), 'candles_1h', ['symbol', 'open_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_1h_symbol_time'), 'candles_1h', ['symbol', 'open_time'], unique=False)
    op.drop_column('candles_1h', 'taker_buy_quote_volume')
    op.drop_column('candles_1h', 'taker_buy_base_volume')
    op.drop_column('candles_1h', 'last_trade_id')
    op.drop_column('candles_1h', 'first_trade_id')
    op.add_column('candles_1d', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_1d_symbol_time'), 'candles_1d', ['symbol', 'open_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_1d_symbol_time'), 'candles_1d', ['symbol', 'open_time'], unique=False)
    op.drop_column('candles_1d', 'taker_buy_quote_volume')
    op.drop_column('candles_1d', 'taker_buy_base_volume')
    op.drop_column('candles_1d', 'last_trade_id')
    op.drop_column('candles_1d', 'first_trade_id')
    op.add_column('candles_15m', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_15m_symbol_time'), 'candles_15m', ['symbol', 'open_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_15m_symbol_time'), 'candles_15m', ['symbol', 'open_time'], unique=False)
    op.drop_column('candles_15m', 'taker_buy_quote_volume')
    op.drop_column('candles_15m', 'taker_buy_base_volume')
    op.drop_column('candles_15m', 'last_trade_id')
    op.drop_column('candles_15m', 'first_trade_id')
    # ### end Alembic commands ###
