"""fresh candle tables baseline

Revision ID: 257401d4ec58
Revises: ed73f3c4c31b
Create Date: 2026-02-27 03:46:16.395242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257401d4ec58'
down_revision: Union[str, Sequence[str], None] = 'ed73f3c4c31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('candles_15m', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('candles_15m', sa.Column('oi_delta_percent', sa.Float(), nullable=True))
    op.add_column('candles_1d', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('candles_1d', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('candles_1d', sa.Column('oi_delta_percent', sa.Float(), nullable=True))
    op.add_column('candles_1h', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('candles_1h', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('candles_1h', sa.Column('oi_delta_percent', sa.Float(), nullable=True))
    op.add_column('candles_1m', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('candles_1m', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('candles_1m', sa.Column('oi_delta_percent', sa.Float(), nullable=True))
    op.add_column('candles_2m', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('candles_2m', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('candles_2m', sa.Column('oi_delta_percent', sa.Float(), nullable=True))
    op.add_column('candles_4h', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('candles_4h', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('candles_4h', sa.Column('oi_delta_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_4h', 'oi_delta_percent')
    op.drop_column('candles_4h', 'funding_rate')
    op.drop_column('candles_4h', 'open_interest')
    op.drop_column('candles_2m', 'oi_delta_percent')
    op.drop_column('candles_2m', 'funding_rate')
    op.drop_column('candles_2m', 'open_interest')
    op.drop_column('candles_1m', 'oi_delta_percent')
    op.drop_column('candles_1m', 'funding_rate')
    op.drop_column('candles_1m', 'open_interest')
    op.drop_column('candles_1h', 'oi_delta_percent')
    op.drop_column('candles_1h', 'funding_rate')
    op.drop_column('candles_1h', 'open_interest')
    op.drop_column('candles_1d', 'oi_delta_percent')
    op.drop_column('candles_1d', 'funding_rate')
    op.drop_column('candles_1d', 'open_interest')
    op.drop_column('candles_15m', 'oi_delta_percent')
    op.drop_column('candles_15m', 'funding_rate')
    op.drop_column('candles_15m', 'open_interest')
    # ### end Alembic commands ###
