"""fresh candle tables baseline

Revision ID: 25dace1276d6
Revises: c6b3e09c3b11
Create Date: 2026-02-13 14:23:15.600366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25dace1276d6'
down_revision: Union[str, Sequence[str], None] = 'c6b3e09c3b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('lc_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('candles_15m', 'latest_candle_at')
    op.add_column('candles_1d', sa.Column('lc_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('candles_1d', 'latest_candle_at')
    op.add_column('candles_1h', sa.Column('lc_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('candles_1h', 'latest_candle_at')
    op.add_column('candles_1m', sa.Column('lc_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('candles_1m', 'latest_candle_at')
    op.add_column('candles_4h', sa.Column('lc_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('candles_4h', 'latest_candle_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_4h', sa.Column('latest_candle_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('candles_4h', 'lc_at')
    op.add_column('candles_1m', sa.Column('latest_candle_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('candles_1m', 'lc_at')
    op.add_column('candles_1h', sa.Column('latest_candle_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('candles_1h', 'lc_at')
    op.add_column('candles_1d', sa.Column('latest_candle_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('candles_1d', 'lc_at')
    op.add_column('candles_15m', sa.Column('latest_candle_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('candles_15m', 'lc_at')
    # ### end Alembic commands ###
