"""oi table

Revision ID: 49e77708d065
Revises: 257401d4ec58
Create Date: 2026-02-28 17:36:45.304433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e77708d065'
down_revision: Union[str, Sequence[str], None] = '257401d4ec58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_interest_1h',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('oi_notional', sa.Float(), nullable=False),
    sa.Column('open_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time')
    )
    op.drop_index(op.f('ix_candles_1d_id'), table_name='candles_1d')
    op.drop_table('candles_1d')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_1d',
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('interval', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('close_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_trade_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_trade_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('taker_buy_base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('taker_buy_quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trade_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('lk_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oi_delta_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time', name=op.f('candles_1d_pkey'))
    )
    op.create_index(op.f('ix_candles_1d_id'), 'candles_1d', ['id'], unique=True)
    op.drop_table('open_interest_1h')
    # ### end Alembic commands ###
