"""drop

Revision ID: 4d9e7fb26a66
Revises: b8dff3d4d677
Create Date: 2026-03-01 02:43:59.008661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9e7fb26a66'
down_revision: Union[str, Sequence[str], None] = 'b8dff3d4d677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_1d',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('lk_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_time', sa.BigInteger(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('first_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('last_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'open_time')
    )
    op.create_index(op.f('ix_candles_1d_id'), 'candles_1d', ['id'], unique=True)
    op.drop_column('candles_15m', 'open_interest')
    op.drop_column('candles_15m', 'oi_delta_percent')
    op.drop_column('candles_15m', 'funding_rate')
    op.drop_column('candles_1h', 'open_interest')
    op.drop_column('candles_1h', 'oi_delta_percent')
    op.drop_column('candles_1h', 'funding_rate')
    op.drop_column('candles_1m', 'open_interest')
    op.drop_column('candles_1m', 'oi_delta_percent')
    op.drop_column('candles_1m', 'funding_rate')
    op.drop_column('candles_2m', 'open_interest')
    op.drop_column('candles_2m', 'oi_delta_percent')
    op.drop_column('candles_2m', 'funding_rate')
    op.drop_column('candles_4h', 'open_interest')
    op.drop_column('candles_4h', 'oi_delta_percent')
    op.drop_column('candles_4h', 'funding_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_4h', sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_4h', sa.Column('oi_delta_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_4h', sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_2m', sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_2m', sa.Column('oi_delta_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_2m', sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_1m', sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_1m', sa.Column('oi_delta_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_1m', sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_1h', sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_1h', sa.Column('oi_delta_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_1h', sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_15m', sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_15m', sa.Column('oi_delta_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candles_15m', sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_candles_1d_id'), table_name='candles_1d')
    op.drop_table('candles_1d')
    # ### end Alembic commands ###
