"""fresh candle tables baseline

Revision ID: 535cf59da3b8
Revises: 1ba0af329c81
Create Date: 2026-02-13 16:28:38.830476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '535cf59da3b8'
down_revision: Union[str, Sequence[str], None] = '1ba0af329c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_15m', 'lc_at')
    op.drop_column('candles_1d', 'lc_at')
    op.drop_column('candles_1h', 'lc_at')
    op.drop_column('candles_1m', 'lc_at')
    op.drop_column('candles_4h', 'lc_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_4h', sa.Column('lc_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('candles_1m', sa.Column('lc_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('candles_1h', sa.Column('lc_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('candles_1d', sa.Column('lc_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('candles_15m', sa.Column('lc_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
