"""add models

Revision ID: 5b1d76eece0c
Revises: 2116e08072b5
Create Date: 2026-02-08 00:56:19.818237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1d76eece0c'
down_revision: Union[str, Sequence[str], None] = '2116e08072b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('candles_1d', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('candles_1h', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('candles_1m', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('candles_4h', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_4h', 'created_at')
    op.drop_column('candles_1m', 'created_at')
    op.drop_column('candles_1h', 'created_at')
    op.drop_column('candles_1d', 'created_at')
    op.drop_column('candles_15m', 'created_at')
    # ### end Alembic commands ###
