"""add cdx candle tables

Revision ID: 79461d16d626
Revises: 8eb1316b4529
Create Date: 2026-02-06 17:57:12.016510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79461d16d626'
down_revision: Union[str, Sequence[str], None] = '8eb1316b4529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdx_candles_1m',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'open_time', name='uq_cdx_1m_symbol_time')
    )
    op.create_index('ix_cdx_1m_symbol_time', 'cdx_candles_1m', ['symbol', 'open_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cdx_1m_symbol_time', table_name='cdx_candles_1m')
    op.drop_table('cdx_candles_1m')
    # ### end Alembic commands ###
