"""add cdx candle tables

Revision ID: 8608dc06723d
Revises: 47021e70803a
Create Date: 2026-02-06 20:39:25.992515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8608dc06723d'
down_revision: Union[str, Sequence[str], None] = '47021e70803a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdx_candles_15m', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cdx_candles_1d', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cdx_candles_1h', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cdx_candles_1m', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cdx_candles_4h', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdx_candles_4h', 'created_at')
    op.drop_column('cdx_candles_1m', 'created_at')
    op.drop_column('cdx_candles_1h', 'created_at')
    op.drop_column('cdx_candles_1d', 'created_at')
    op.drop_column('cdx_candles_15m', 'created_at')
    # ### end Alembic commands ###
