"""add models

Revision ID: 8eb1316b4529
Revises: 17932b9b43e4
Create Date: 2026-02-03 00:48:26.743302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb1316b4529'
down_revision: Union[str, Sequence[str], None] = '17932b9b43e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_15m',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'open_time', name='uq_15m_symbol_time')
    )
    op.create_index('ix_15m_symbol_time', 'candles_15m', ['symbol', 'open_time'], unique=False)
    op.create_table('candles_1d',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'open_time', name='uq_1d_symbol_time')
    )
    op.create_index('ix_1d_symbol_time', 'candles_1d', ['symbol', 'open_time'], unique=False)
    op.create_table('candles_1h',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'open_time', name='uq_1h_symbol_time')
    )
    op.create_index('ix_1h_symbol_time', 'candles_1h', ['symbol', 'open_time'], unique=False)
    op.create_table('candles_4h',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('base_volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'open_time', name='uq_4h_symbol_time')
    )
    op.create_index('ix_4h_symbol_time', 'candles_4h', ['symbol', 'open_time'], unique=False)
    op.drop_index(op.f('ix_candles_1m_symbol_interval_open_time'), table_name='candles_1m')
    op.drop_constraint(op.f('uq_candles_1m_symbol_interval_open_time'), 'candles_1m', type_='unique')
    op.create_index('ix_1m_symbol_time', 'candles_1m', ['symbol', 'open_time'], unique=False)
    op.create_unique_constraint('uq_1m_symbol_time', 'candles_1m', ['symbol', 'open_time'])
    op.drop_column('candles_1m', 'last_trade_id')
    op.drop_column('candles_1m', 'event_type')
    op.drop_column('candles_1m', 'interval')
    op.drop_column('candles_1m', 'taker_quote_volume')
    op.drop_column('candles_1m', 'ignore')
    op.drop_column('candles_1m', 'first_trade_id')
    op.drop_column('candles_1m', 'taker_base_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_1m', sa.Column('taker_base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('candles_1m', sa.Column('first_trade_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('candles_1m', sa.Column('ignore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('candles_1m', sa.Column('taker_quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('candles_1m', sa.Column('interval', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('candles_1m', sa.Column('event_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('candles_1m', sa.Column('last_trade_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_1m_symbol_time', 'candles_1m', type_='unique')
    op.drop_index('ix_1m_symbol_time', table_name='candles_1m')
    op.create_unique_constraint(op.f('uq_candles_1m_symbol_interval_open_time'), 'candles_1m', ['symbol', 'interval', 'open_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_candles_1m_symbol_interval_open_time'), 'candles_1m', ['symbol', 'interval', 'open_time'], unique=False)
    op.drop_index('ix_4h_symbol_time', table_name='candles_4h')
    op.drop_table('candles_4h')
    op.drop_index('ix_1h_symbol_time', table_name='candles_1h')
    op.drop_table('candles_1h')
    op.drop_index('ix_1d_symbol_time', table_name='candles_1d')
    op.drop_table('candles_1d')
    op.drop_index('ix_15m_symbol_time', table_name='candles_15m')
    op.drop_table('candles_15m')
    # ### end Alembic commands ###
