"""add models

Revision ID: a3d5186c5468
Revises: ca77f3e76b5c
Create Date: 2026-02-11 01:10:53.388405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d5186c5468'
down_revision: Union[str, Sequence[str], None] = 'ca77f3e76b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles_15m', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_15m', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_15m', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_15m', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('candles_1d', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1d', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1d', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1d', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('candles_1h', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1h', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1h', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1h', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('candles_1m', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1m', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1m', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_1m', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('candles_4h', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_4h', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_4h', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('candles_4h', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles_4h', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candles_4h', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_4h', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_4h', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1m', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candles_1m', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1m', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1m', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1h', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candles_1h', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1h', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1h', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1d', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candles_1d', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1d', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_1d', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_15m', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candles_15m', 'last_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_15m', 'first_trade_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('candles_15m', 'event_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
