"""add models

Revision ID: a4218c5ee934
Revises: a9c4c9fb818b
Create Date: 2026-02-10 01:53:49.534261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4218c5ee934'
down_revision: Union[str, Sequence[str], None] = 'a9c4c9fb818b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candles_15m_id'), 'candles_15m', ['id'], unique=True)
    op.create_index(op.f('ix_candles_1d_id'), 'candles_1d', ['id'], unique=True)
    op.create_index(op.f('ix_candles_1h_id'), 'candles_1h', ['id'], unique=True)
    op.create_index(op.f('ix_candles_1m_id'), 'candles_1m', ['id'], unique=True)
    op.create_index(op.f('ix_candles_4h_id'), 'candles_4h', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candles_4h_id'), table_name='candles_4h')
    op.drop_index(op.f('ix_candles_1m_id'), table_name='candles_1m')
    op.drop_index(op.f('ix_candles_1h_id'), table_name='candles_1h')
    op.drop_index(op.f('ix_candles_1d_id'), table_name='candles_1d')
    op.drop_index(op.f('ix_candles_15m_id'), table_name='candles_15m')
    # ### end Alembic commands ###
