"""add models

Revision ID: a9c4c9fb818b
Revises: 0d450746331b
Create Date: 2026-02-09 16:44:58.575575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c4c9fb818b'
down_revision: Union[str, Sequence[str], None] = '0d450746331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('interval', sa.String(length=20), nullable=True))
    op.add_column('candles_1d', sa.Column('interval', sa.String(length=20), nullable=True))
    op.add_column('candles_1h', sa.Column('interval', sa.String(length=20), nullable=True))
    op.add_column('candles_1m', sa.Column('interval', sa.String(length=20), nullable=True))
    op.add_column('candles_4h', sa.Column('interval', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_4h', 'interval')
    op.drop_column('candles_1m', 'interval')
    op.drop_column('candles_1h', 'interval')
    op.drop_column('candles_1d', 'interval')
    op.drop_column('candles_15m', 'interval')
    # ### end Alembic commands ###
