"""Fr

Revision ID: b8dff3d4d677
Revises: 49e77708d065
Create Date: 2026-02-28 17:52:39.422123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dff3d4d677'
down_revision: Union[str, Sequence[str], None] = '49e77708d065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_rate_8h',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('funding_time', sa.BigInteger(), nullable=False),
    sa.Column('funding_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.Column('mark_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'funding_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_rate_8h')
    # ### end Alembic commands ###
