"""fresh candle tables baseline

Revision ID: c6b3e09c3b11
Revises: ad41df0ebfdd
Create Date: 2026-02-13 14:16:23.443104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b3e09c3b11'
down_revision: Union[str, Sequence[str], None] = 'ad41df0ebfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('latest_candle_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_1d', sa.Column('latest_candle_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_1h', sa.Column('latest_candle_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_1m', sa.Column('latest_candle_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candles_4h', sa.Column('latest_candle_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_4h', 'latest_candle_at')
    op.drop_column('candles_1m', 'latest_candle_at')
    op.drop_column('candles_1h', 'latest_candle_at')
    op.drop_column('candles_1d', 'latest_candle_at')
    op.drop_column('candles_15m', 'latest_candle_at')
    # ### end Alembic commands ###
