"""add cdx candle tables

Revision ID: c884f1a301af
Revises: 8608dc06723d
Create Date: 2026-02-06 20:40:48.413613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c884f1a301af'
down_revision: Union[str, Sequence[str], None] = '8608dc06723d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdx_candles_15m', 'event_time')
    op.drop_column('cdx_candles_1d', 'event_time')
    op.drop_column('cdx_candles_1h', 'event_time')
    op.drop_column('cdx_candles_1m', 'event_time')
    op.drop_column('cdx_candles_4h', 'event_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdx_candles_4h', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_1m', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_1h', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_1d', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cdx_candles_15m', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
