"""add models

Revision ID: cd160b81ee30
Revises: 5b1d76eece0c
Create Date: 2026-02-08 03:03:25.798951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd160b81ee30'
down_revision: Union[str, Sequence[str], None] = '5b1d76eece0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles_15m', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('candles_1d', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('candles_1h', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('candles_1m', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('candles_4h', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles_4h', 'id')
    op.drop_column('candles_1m', 'id')
    op.drop_column('candles_1h', 'id')
    op.drop_column('candles_1d', 'id')
    op.drop_column('candles_15m', 'id')
    # ### end Alembic commands ###
