"""add cdx candle tables

Revision ID: dcb1b6e00c8f
Revises: 1d9300ad9fe8
Create Date: 2026-02-06 19:36:38.231847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb1b6e00c8f'
down_revision: Union[str, Sequence[str], None] = '1d9300ad9fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdx_candles_15m', sa.Column('event_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cdx_candles_1d', sa.Column('event_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cdx_candles_1h', sa.Column('event_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cdx_candles_1m', sa.Column('event_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cdx_candles_4h', sa.Column('event_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdx_candles_4h', 'event_time')
    op.drop_column('cdx_candles_1m', 'event_time')
    op.drop_column('cdx_candles_1h', 'event_time')
    op.drop_column('cdx_candles_1d', 'event_time')
    op.drop_column('cdx_candles_15m', 'event_time')
    # ### end Alembic commands ###
