"""remove order table

Revision ID: e38d19ff67a8
Revises: b9999585b043
Create Date: 2026-03-17 01:25:30.191160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38d19ff67a8'
down_revision: Union[str, Sequence[str], None] = 'b9999585b043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cdx_1d_symbol_time'), table_name='cdx_candles_1d')
    op.drop_table('cdx_candles_1d')
    op.drop_index(op.f('ix_cdx_4h_symbol_time'), table_name='cdx_candles_4h')
    op.drop_table('cdx_candles_4h')
    op.drop_index(op.f('ix_cdx_1m_symbol_time'), table_name='cdx_candles_1m')
    op.drop_table('cdx_candles_1m')
    op.drop_index(op.f('ix_cdx_1h_symbol_time'), table_name='cdx_candles_1h')
    op.drop_table('cdx_candles_1h')
    op.drop_index(op.f('ix_cdx_15m_symbol_time'), table_name='cdx_candles_15m')
    op.drop_table('cdx_candles_15m')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdx_candles_15m',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('close_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cdx_candles_15m_pkey')),
    sa.UniqueConstraint('symbol', 'open_time', name=op.f('uq_cdx_15m_symbol_time'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cdx_15m_symbol_time'), 'cdx_candles_15m', ['symbol', 'open_time'], unique=False)
    op.create_table('cdx_candles_1h',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('close_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cdx_candles_1h_pkey')),
    sa.UniqueConstraint('symbol', 'open_time', name=op.f('uq_cdx_1h_symbol_time'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cdx_1h_symbol_time'), 'cdx_candles_1h', ['symbol', 'open_time'], unique=False)
    op.create_table('cdx_candles_1m',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('close_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cdx_candles_1m_pkey')),
    sa.UniqueConstraint('symbol', 'open_time', name=op.f('uq_cdx_1m_symbol_time'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cdx_1m_symbol_time'), 'cdx_candles_1m', ['symbol', 'open_time'], unique=False)
    op.create_table('cdx_candles_4h',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('close_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cdx_candles_4h_pkey')),
    sa.UniqueConstraint('symbol', 'open_time', name=op.f('uq_cdx_4h_symbol_time'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cdx_4h_symbol_time'), 'cdx_candles_4h', ['symbol', 'open_time'], unique=False)
    op.create_table('cdx_candles_1d',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('close_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cdx_candles_1d_pkey')),
    sa.UniqueConstraint('symbol', 'open_time', name=op.f('uq_cdx_1d_symbol_time'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cdx_1d_symbol_time'), 'cdx_candles_1d', ['symbol', 'open_time'], unique=False)
    # ### end Alembic commands ###
